### ISSUE TITLE
20221031 placeholder for work

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsopt#136]
Reminder that @gurhar1133 is assigned to this project

**Comment by gurhar1133** [comment]
Is this an issue to find me an issue?

**Comment by cchall** [comment]
I had intended  to have @gurhar1133 take over #64 
Though it's best to wait for Perlmutter support (https://github.com/radiasoft/containers/issues/106) as the issue might end up being Cori specific. In that case we can re-evaluate for Perlmutter since Cori won't be around much longer.

**Comment by robnagler** [comment]
I don't think #64 is Perlmutter specific.

**Comment by cchall** [comment]
Sorry, you are correct, the direct issue of checking for mpi4py import is not really Perlmutter specific.
However, the reason to do this check in the first place is due to Cori's restriction on one job per node. So to ensure #56 doesn't result in launching to an already used node you need to check for nodes that are occupied, which in turn will require communication over MPI - if it is being used - so you have to check.
